# Generated by Django 2.1.5 on 2019-01-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.PolicyCard', verbose_name='政策卡'),
        ),
        migrations.AlterField(
            model_name='policycard',
            name='policy_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='政策编号'),
        ),
    ]
