# Generated by Django 2.1.5 on 2019-01-20 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='企业类型')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='成立时间')),
                ('emp_num', models.IntegerField(blank=True, null=True, verbose_name='最低企业员工数量')),
                ('tech_emp_num', models.IntegerField(blank=True, null=True, verbose_name='最低技术人员数量')),
                ('total_assets', models.FloatField(blank=True, null=True, verbose_name='最低总资产(万)')),
                ('fixed_assets', models.FloatField(blank=True, null=True, verbose_name='最低固定资产（万）')),
                ('sales_profit', models.FloatField(blank=True, null=True, verbose_name='最低销售收入（万）')),
                ('sales_mainly_prop', models.FloatField(blank=True, null=True, verbose_name='最低主导产品收入占比(百分比)')),
                ('sales_profit_inc', models.FloatField(blank=True, null=True, verbose_name='最低销售收入增长率(百分比)')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='最低利润（万）')),
                ('profit_inc', models.FloatField(blank=True, null=True, verbose_name='最低利润增长率（百分百）')),
                ('research_cost_prop', models.FloatField(blank=True, null=True, verbose_name='最低研发投入占比(百分比)')),
                ('patent_num', models.IntegerField(blank=True, null=True, verbose_name='最低专利数量')),
                ('intellectual_property', models.IntegerField(blank=True, null=True, verbose_name='其他知识产权数量')),
            ],
            options={
                'verbose_name': '企业资质信息',
                'verbose_name_plural': '企业资质信息',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=20, verbose_name='政策编号')),
                ('policy_title', models.CharField(max_length=50, verbose_name='政策标题')),
                ('policy_content', models.TextField(verbose_name='政策全文')),
                ('policy_url', models.URLField(blank=True, null=True, verbose_name='政策网址')),
            ],
            options={
                'verbose_name': '政策详细信息',
                'verbose_name_plural': '政策详细信息',
            },
        ),
        migrations.CreateModel(
            name='PolicyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='政策卡标题')),
                ('reward_content', models.CharField(max_length=500, verbose_name='奖补内容')),
                ('policy_basis', models.CharField(max_length=500, verbose_name='政策依据')),
                ('policy_conditions', models.CharField(max_length=500, verbose_name='申报条件')),
                ('apply_time', models.DateField(default=datetime.date.today, verbose_name='申请时间')),
                ('policy_level', models.IntegerField(choices=[(0, '省级'), (1, '县级'), (2, '县（市， 区）级')], default=0, verbose_name='政策层级')),
                ('policy_type', models.IntegerField(choices=[(0, '综合类'), (1, '资金奖补类'), (2, '税收费用减免类'), (3, '资质荣誉类')], default=0, verbose_name='政策类型')),
                ('policy_area', models.CharField(max_length=20, verbose_name='政策区域')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.Company', verbose_name='企业资质')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.Policy', verbose_name='相关政策')),
            ],
            options={
                'verbose_name': '政策卡',
                'verbose_name_plural': '政策卡',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
