# Generated by Django 2.1.5 on 2019-01-22 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycard',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='政策卡标题'),
        ),
        migrations.AlterField(
            model_name='policycard',
            name='apply_time',
            field=models.DateField(default=datetime.date.today, verbose_name='政策申报时间'),
        ),
        migrations.AlterField(
            model_name='policycard',
            name='create_date',
            field=models.DateField(blank=True, null=True, verbose_name='企业成立时间'),
        ),
        migrations.AlterField(
            model_name='policycard',
            name='policy_conditions',
            field=models.TextField(max_length=500, verbose_name='政策申报条件'),
        ),
    ]
