# Generated by Django 2.1.5 on 2019-01-29 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20190122_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policycard',
            name='apply_time',
        ),
        migrations.RemoveField(
            model_name='policycard',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='policycard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='policycard',
            name='policy',
        ),
        migrations.AddField(
            model_name='policycard',
            name='create_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='成立年限(年)'),
        ),
        migrations.AddField(
            model_name='policycard',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='policycard',
            name='policy_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False, verbose_name='政策编号'),
        ),
        migrations.AlterField(
            model_name='policycard',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
