# Generated by Django 2.1.5 on 2019-01-29 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20190129_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('download', models.FileField(upload_to='policy/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.PolicyCard', verbose_name='政策卡')),
            ],
            options={
                'verbose_name': '政策卡文件资源',
                'verbose_name_plural': '政策卡文件资源',
            },
        ),
    ]
