# Generated by Django 2.1.5 on 2019-01-29 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_policyresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '一类专利'), (1, '二类专利'), (2, '三类专利'), (3, '其他')], verbose_name='专利类型')),
                ('number', models.IntegerField(verbose_name='专利数量')),
            ],
        ),
        migrations.RemoveField(
            model_name='policycard',
            name='intellectual_property',
        ),
        migrations.RemoveField(
            model_name='policycard',
            name='patent_num',
        ),
        migrations.AlterField(
            model_name='policycard',
            name='end_time',
            field=models.DateField(default=datetime.date.today, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='policycard',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='policyresource',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='policyresource',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.PolicyCard', verbose_name='所属政策卡'),
        ),
        migrations.AlterField(
            model_name='policyresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='文件名称'),
        ),
        migrations.AddField(
            model_name='patentlimit',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.PolicyCard', verbose_name='所属政策卡'),
        ),
    ]
