# Generated by Django 2.1.5 on 2019-01-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20190129_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num', models.IntegerField(verbose_name='最大员工数量')),
                ('max_flag', models.BooleanField(verbose_name='是否包括最大数量')),
                ('min_num', models.IntegerField(verbose_name='最小员工数量')),
                ('min_flag', models.BooleanField(verbose_name='是否包括最小数量')),
                ('tech_emp_prop', models.FloatField(verbose_name='技术人员占比')),
                ('bachelor_prop', models.FloatField(blank=True, null=True, verbose_name='本科学历占比')),
                ('master_prop', models.FloatField(blank=True, null=True, verbose_name='硕士及以上学历占比')),
            ],
            options={
                'verbose_name': '员工限制',
                'verbose_name_plural': '员工限制',
            },
        ),
        migrations.AlterModelOptions(
            name='patentlimit',
            options={'verbose_name': '专利限制', 'verbose_name_plural': '专利限制'},
        ),
        migrations.RemoveField(
            model_name='policycard',
            name='emp_num',
        ),
        migrations.RemoveField(
            model_name='policycard',
            name='tech_emp_num',
        ),
        migrations.AddField(
            model_name='stafflimit',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.PolicyCard', verbose_name='所属政策卡'),
        ),
    ]
